import { useFocusEffect } from '@react-navigation/native';
import { useCallback, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ApiError, request } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { Button, Card, ErrorBanner, Input, Screen, SelectChips, SectionTitle, pretty } from '../components/ui';
import { colors } from '../theme';
import { Role, Tool, UserSummary } from '../types';
import { passwordRequirements, validatePassword } from '../validation';
const roles: Role[] = ['EMPLOYEE', 'MANAGER'];
export function EmployeesScreen() {
  const { session } = useAuth(); const [employees, setEmployees] = useState<UserSummary[]>([]); const [tools, setTools] = useState<Tool[]>([]); const [selected, setSelected] = useState<UserSummary>(); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ name: '', email: '', password: '', role: 'EMPLOYEE' as Role }); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const canManage = session?.user.role !== 'EMPLOYEE';
  const load = useCallback(() => Promise.all([
    request<UserSummary[]>('/api/employees', {}, session?.token),
    request<Tool[]>('/api/tools', {}, session?.token),
  ]).then(([users, companyTools]) => { setEmployees(users); setTools(companyTools); }).catch(e => setError(e.message)), [session?.token]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  async function add() { if (!form.name || !form.email || !form.password) return setError('Complete every employee field.'); const passwordError = validatePassword(form.password); if (passwordError) return setError(passwordError); setLoading(true); setError(''); try { await request<UserSummary>('/api/employees', { method: 'POST', body: JSON.stringify(form) }, session?.token); setForm({ name: '', email: '', password: '', role: 'EMPLOYEE' }); setShowForm(false); load(); } catch (e) { setError(e instanceof ApiError ? e.message : 'Could not add employee.'); } finally { setLoading(false); } }
  return <Screen><View style={styles.header}><View><Text style={styles.count}>{employees.length}</Text><Text style={styles.countLabel}>active team members</Text></View><Pressable onPress={() => setShowForm(value => !value)} style={styles.add}><Text style={styles.addText}>{showForm ? '×' : '＋'}</Text></Pressable></View><ErrorBanner message={error} />
    {showForm && <Card style={{ gap: 13 }}><SectionTitle title="New team member" /><Input label="Name" value={form.name} onChangeText={name => setForm(v => ({ ...v, name }))} /><Input label="Email" value={form.email} onChangeText={email => setForm(v => ({ ...v, email }))} autoCapitalize="none" keyboardType="email-address" /><Input label="Temporary password" value={form.password} onChangeText={password => setForm(v => ({ ...v, password }))} secureTextEntry placeholder="Strong temporary password" autoComplete="new-password" /><Text style={styles.passwordHelp}>{passwordRequirements}</Text><SelectChips label="Role" value={form.role} options={roles} onChange={role => setForm(v => ({ ...v, role }))} /><Button title="Add employee" onPress={add} loading={loading} /></Card>}
    <SectionTitle title="Crew" />{employees.map(employee => <Pressable key={employee.id} disabled={!canManage} onPress={() => setSelected(employee)} accessibilityRole={canManage ? 'button' : undefined}><Card style={styles.employee}><View style={styles.avatar}><Text style={styles.avatarText}>{employee.name.split(' ').map(p => p[0]).join('').slice(0, 2).toUpperCase()}</Text></View><View style={{ flex: 1 }}><Text style={styles.name}>{employee.name}</Text><Text style={styles.email}>{employee.email}</Text></View><View style={styles.role}><Text style={styles.roleText}>{pretty(employee.role)}</Text></View>{canManage && <Text style={styles.chevron}>›</Text>}</Card></Pressable>)}
    <EmployeeDetails employee={selected} tools={tools.filter(tool => tool.checkedOutTo?.id === selected?.id)} onClose={() => setSelected(undefined)} />
  </Screen>;
}

function EmployeeDetails({ employee, tools, onClose }: { employee?: UserSummary; tools: Tool[]; onClose(): void }) {
  return <Modal visible={!!employee} transparent animationType="slide" onRequestClose={onClose}><View style={styles.modalBackdrop}><SafeAreaView style={styles.modalSafe}><View style={styles.modalCard}><ScrollView contentContainerStyle={styles.modalContent}><View style={styles.modalHeader}><View><Text style={styles.modalEyebrow}>TEAM MEMBER</Text><Text style={styles.modalName}>{employee?.name}</Text></View><Pressable onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View><View style={styles.infoRow}><Text style={styles.infoLabel}>Email</Text><Text selectable style={styles.infoValue}>{employee?.email}</Text></View><View style={styles.infoRow}><Text style={styles.infoLabel}>Role</Text><Text style={styles.infoValue}>{pretty(employee?.role)}</Text></View><View style={styles.infoRow}><Text style={styles.infoLabel}>Status</Text><Text style={styles.infoValue}>{employee?.active ? 'Active' : 'Inactive'}</Text></View><SectionTitle title={`Tools currently held · ${tools.length}`} />{tools.map(tool => <Card key={tool.id}><Text style={styles.toolAsset}>{tool.assetNumber}</Text><Text style={styles.toolName}>{tool.name}</Text><Text style={styles.email}>{tool.currentLocation || 'No location recorded'}</Text></Card>)}{!tools.length && <Text style={styles.emptyText}>No tools are currently checked out to this employee.</Text>}<Button title="Close" variant="secondary" onPress={onClose} /></ScrollView></View></SafeAreaView></View></Modal>;
}

const styles = StyleSheet.create({ header: { borderRadius: 20, padding: 20, backgroundColor: colors.navy, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, count: { color: '#fff', fontWeight: '900', fontSize: 34 }, countLabel: { color: '#B8C4CA' }, add: { width: 48, height: 48, borderRadius: 15, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' }, addText: { color: '#fff', fontWeight: '800', fontSize: 27 }, employee: { flexDirection: 'row', alignItems: 'center', gap: 12 }, avatar: { width: 46, height: 46, borderRadius: 15, backgroundColor: colors.paleBlue, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.blue, fontWeight: '900' }, name: { color: colors.ink, fontWeight: '800' }, email: { color: colors.muted, fontSize: 12, marginTop: 2 }, role: { borderRadius: 100, backgroundColor: colors.paleOrange, paddingHorizontal: 9, paddingVertical: 6 }, roleText: { color: colors.orangeDark, fontWeight: '800', fontSize: 10 }, chevron: { color: colors.muted, fontSize: 26 }, passwordHelp: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: -7 }, modalBackdrop: { flex: 1, backgroundColor: 'rgba(10, 24, 33, .5)', justifyContent: 'flex-end' }, modalSafe: { maxHeight: '88%', backgroundColor: colors.paper, borderTopLeftRadius: 24, borderTopRightRadius: 24 }, modalCard: { borderTopLeftRadius: 24, borderTopRightRadius: 24, overflow: 'hidden' }, modalContent: { padding: 20, gap: 14, paddingBottom: 28 }, modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, modalEyebrow: { color: colors.orangeDark, fontWeight: '900', fontSize: 10, letterSpacing: 1.3 }, modalName: { color: colors.ink, fontWeight: '900', fontSize: 26, marginTop: 4 }, close: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.paleBlue, alignItems: 'center', justifyContent: 'center' }, closeText: { color: colors.navy, fontSize: 26, lineHeight: 29 }, infoRow: { borderBottomWidth: 1, borderBottomColor: colors.line, paddingVertical: 10, gap: 4 }, infoLabel: { color: colors.muted, fontSize: 11, fontWeight: '700' }, infoValue: { color: colors.ink, fontSize: 16, fontWeight: '700' }, toolAsset: { color: colors.orangeDark, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, toolName: { color: colors.ink, fontSize: 16, fontWeight: '800', marginTop: 3 }, emptyText: { color: colors.muted, textAlign: 'center', lineHeight: 20, paddingVertical: 18 } });
